### ISSUE TITLE
I would like to ask how to install this software?

### ISSUE THREAD

**Issue by a5226032** [Coding-Enthusiast/BitcoinTransactionTool#10]

**Comment by a5226032** [comment]
My computer seems to be missing something. After downloading, it is difficult to install and open the software

**Comment by Coding-Enthusiast** [comment]
This project runs only on Windows and you need to have .net framework 4.6 installed.

**Comment by a5226032** [comment]
Still need to download Denovo?

**Comment by Coding-Enthusiast** [comment]
Denovo is a separate and different project. Has nothing to do with running this application.

**Comment by a5226032** [comment]
Download this software and. NET Framework 4.6 and can run it, right?

**Comment by a5226032** [comment]
Download this software and. NET Framework 4.6 and can run it, right

**Comment by a5226032** [comment]
Can the software actually send bitcoins to a wallet?    can also set the lifetime of the bitcoin?

**Comment by a5226032** [comment]
How many Bitcoins could be generated per day if they could be generated and sent? What's the survival period?

**Comment by a5226032** [comment]
Is this a fake bitcoin generator

**Comment by a5226032** [comment]
Are you there, brother

**Comment by Coding-Enthusiast** [comment]
> Is this a fake bitcoin generator

No! Take another look at the ReadMe.
