### ISSUE TITLE
Build errors in Visual Studio Code

### ISSUE THREAD

**Issue by maxcado** [Coding-Enthusiast/BitcoinTransactionTool#5]
I've tried to build this tool using Visual Studio Code 2015. Installed the dependencies. Everything looked okay until the build stage. I get the following errors:

 1>------ Build started: Project: CommonLibrary, Configuration: Debug Any CPU ------
1>C:\Users\user\Videos\Money\BitcoinTransactionTool-master\CommonLibrary\CryptoEncoders\Bech32.cs(175,67,175,73): error CS1525: Invalid expression term 'string'
1>C:\Users\user\Videos\Money\BitcoinTransactionTool-master\CommonLibrary\CryptoEncoders\Bech32.cs(175,74,175,77): error CS1003: Syntax error, ',' expected
1>C:\Users\user\Videos\Money\BitcoinTransactionTool-master\CommonLibrary\CryptoEncoders\Base58.cs(199,65,199,74): error CS1003: Syntax error, ',' expected
1>C:\Users\user\Videos\Money\BitcoinTransactionTool-master\CommonLibrary\Transaction\TxIn.cs(10,40,10,42): error CS1043: { or ; expected
1>C:\Users\user\Videos\Money\BitcoinTransactionTool-master\CommonLibrary\Transaction\TxIn.cs(10,40,10,42): error CS1513: } expected
1>C:\Users\user\Videos\Money\BitcoinTransactionTool-master\CommonLibrary\Transaction\TxIn.cs(10,81,10,81): error CS1513: } expected
2>------ Build started: Project: BitcoinTransactionTool, Configuration: Debug Any CPU ------
2>CSC : error CS0006: Metadata file 'C:\Users\user\Videos\Money\BitcoinTransactionTool-master\CommonLibrary\bin\Debug\CommonLibrary.dll' could not be found
3>------ Skipped Publish: Project BitcoinTransactionTool, Configuration: Debug Any CPU ------
3> 
========== Build: 0 succeeded, 2 failed, 0 up-to-date, 0 skipped ==========
========== Publish: 0 succeeded, 0 failed, 1 skipped ==========

**Comment by Coding-Enthusiast** [comment]
This is a compiler issue. You need to upgrade your compiler for C# 7.

All these errors are occurring on [new C# features](https://blogs.msdn.microsoft.com/dotnet/2017/03/09/new-features-in-c-7-0/). 

For example line 175 and 205 in Bech32.cs file is a new feature where it allows you to declare a variable right where you pass it in a function. Alternative way of fixing it is to edit the code to something like this:

    string hrp = string.Empty;
    byte[] b32Arr = Bech32Decode(bech32EncodedString, out hrp);
